### ISSUE TITLE
File to import not found or unreadable: @angular/material/core/theming/all-theme

### ISSUE THREAD

**Issue by AKamanjha** [DmitriyPotapov/angular-seed-inspinia#1]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
While installing node modules , i am getting error 
on line 1 of src/client/scss/material.scss
>> @import '@angular/material/core/theming/all-theme';

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by DmitriyPotapov** [comment]
Fixed

**Comment by DmitriyPotapov** [comment]
Fixed, after general update
